services:
  app:
    image: vaulter:latest
    build: .
    environment:
      VAULTER_APP: Development
    command: python3 -m flask --app vaulter --debug run --host=0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - .:/app