# Flask constants
ALLOWED_EXTENSIONS = ['vault']

# Environment variables provided by Divio
# https://www.divio.com/
DEFAULT_STORAGE_ACCESS_KEY_ID = 'DEFAULT_STORAGE_ACCESS_KEY_ID'
DEFAULT_STORAGE_BUCKET = 'DEFAULT_STORAGE_BUCKET'
DEFAULT_STORAGE_SECRET_ACCESS_KEY = 'DEFAULT_STORAGE_SECRET_ACCESS_KEY'
DEFAULT_STORAGE_REGION = 'DEFAULT_STORAGE_REGION'